In [22]:
import pandas as pd
import numpy as np
import math

In [23]:
df = pd.read_excel('HNSCC_Patient_Samples.xlsx', header = 1)
df

,QC,Patient ID,Source,Diagnosis,Ship Date,Ship/Draw Time (CST),Staining Date,Staining Time (PST),Total Volume (ml),Volume for Staining,...,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage,Unnamed: 38
0,NaN,Head and Neck Squamous Cell Carcinoma,NaN,Blue-do we have this info?,Yellow-ask for from KUMC,"Orange-Ok sample, consider excluding",Red-Bad/not received sample,Not available,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.cancer.org/cancer/types/oral-cavit...,NaN
1,NaN,616919,KUMC,HNSCC,2025-08-04 00:00:00,6:43am,2025-08-05 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT4aN0,negative,4,NaN
2,NaN,611553,KUMC,HNSCC,2024-04-11 00:00:00,6:42am,2024-04-12 00:00:00,2:55pm,7.3,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, well-to moderately di...",Squamous cell carcinoma,"Tongue/oral cavity, Pharynx",negative,NaN,pT4a N0 M (N/A),negative,3,NaN
3,NaN,611620,KUMC,HNSCC,2024-04-18 00:00:00,6:30am,2024-04-19 00:00:00,11:55am,9.0,1.0,...,Not Hispanic or Latino,HPV-mediated squamous cell carcinoma of the ri...,HPV mediated squamous cell carcinoma,Tonsil,NaN,Positive,NaN,NaN,NaN,NaN
4,Good,614851,KUMC,HNSCC,2025-02-17 00:00:00,7:40am,2025-02-18 00:00:00,12:15pm,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,tongue,NaN,NaN,pT1pN0,negative,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,Ok,602635,KUMC,Healthy,2024-12-10 00:00:00,1:33pm,2024-12-11 00:00:00,1:30pm,8.7,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Not HNSCC,616519,KUMC,NaN,2025-06-25 00:00:00,11:05am,2025-06-26 00:00:00,NaN,10.0,1.0,...,Not Hispanic or Latino,Gastric hyperplastic polyp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Arrived Late,612062,KUMC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,Arrived Late,617101,KUMC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df.drop(range(44, 87), inplace = True)
df

,QC,Patient ID,Source,Diagnosis,Ship Date,Ship/Draw Time (CST),Staining Date,Staining Time (PST),Total Volume (ml),Volume for Staining,...,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage,Unnamed: 38
0,NaN,Head and Neck Squamous Cell Carcinoma,NaN,Blue-do we have this info?,Yellow-ask for from KUMC,"Orange-Ok sample, consider excluding",Red-Bad/not received sample,Not available,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.cancer.org/cancer/types/oral-cavit...,NaN
1,NaN,616919,KUMC,HNSCC,2025-08-04 00:00:00,6:43am,2025-08-05 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT4aN0,negative,4,NaN
2,NaN,611553,KUMC,HNSCC,2024-04-11 00:00:00,6:42am,2024-04-12 00:00:00,2:55pm,7.3,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, well-to moderately di...",Squamous cell carcinoma,"Tongue/oral cavity, Pharynx",negative,NaN,pT4a N0 M (N/A),negative,3,NaN
3,NaN,611620,KUMC,HNSCC,2024-04-18 00:00:00,6:30am,2024-04-19 00:00:00,11:55am,9.0,1.0,...,Not Hispanic or Latino,HPV-mediated squamous cell carcinoma of the ri...,HPV mediated squamous cell carcinoma,Tonsil,NaN,Positive,NaN,NaN,NaN,NaN
4,Good,614851,KUMC,HNSCC,2025-02-17 00:00:00,7:40am,2025-02-18 00:00:00,12:15pm,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,tongue,NaN,NaN,pT1pN0,negative,1,NaN
5,Good,614476,KUMC,HNSCC,2025-01-21 00:00:00,7:13am,2025-01-22 00:00:00,10:20am,9.0,1.0,...,Not Hispanic or Latino,"Invasive, moderately differentiated keratiniz...",Squamous cell carcinoma,Lip,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,617177,KUMC,HNSCC,2025-08-26 00:00:00,6:28am,2025-08-27 00:00:00,2:00pm,8.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,"Oral mucosa, tongue",NaN,NaN,pT4aN3b,positive,4,NaN
7,NaN,611603,KUMC,HNSCC,2024-04-17 00:00:00,9:48am,2024-04-18 00:00:00,10:45am,6.2,1.0,...,Not Hispanic or Latino,"invasive squamous cell carcinoma, well to mode...",Invasive squamous cell carcinoma,Tongue,negative,NaN,NaN,NaN,NaN,NaN
8,NaN,616671,KUMC,HNSCC,2025-07-14 00:00:00,7:25am,2025-07-15 00:00:00,11:00am,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, with po...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,negative,NaN,NaN,NaN,NaN
9,NaN,616701,KUMC,HNSCC,2025-07-15 00:00:00,6:24am,2025-07-16 00:00:00,12:00pm,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,NaN,pT4aN0,negative,4,NaN
10,NaN,615538,KUMC,HNSCC,2025-04-09 00:00:00,6:14am,2025-04-10 00:00:00,12:15pm,9.0,1.0,...,Not Hispanic or Latino,Moderately differentiated squamous cell carcin...,Squamous cell carcinoma,gingival mucosa,NaN,NaN,pT2pN0,negative,2,NaN
11,Good,615576,KUMC,HNSCC,2025-04-14 00:00:00,8:30am,2025-04-15 00:00:00,10:00am,6.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, invasive, keratinizin...",Squamous cell carcinoma,tongue,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,616494,KUMC,HNSCC,2025-06-25 00:00:00,6:38am,2025-06-26 00:00:00,NaN,8.0,1.0,...,Not Hispanic or Latino,Human papillomavirus (HPV)-associated squamous...,HPV mediated squamous cell carcinoma,Tonsil,NaN,postive,pT2pN2,postitive,4,NaN
13,NaN,616343,KUMC,HNSCC,2025-06-09 00:00:00,6:58am,2025-06-10 00:00:00,1:30pm,3.0,1.0,...,Not Hispanic or Latino,Squamous cell carcinoma,Squamous cell carcinoma of the oral cavity,"Neck, Oral cavity",NaN,NaN,pT2pN1,Positive,3,NaN
14,NaN,616861,KUMC,HNSCC,2025-07-29 00:00:00,6:39am,2025-07-30 00:00:00,12:30pm,8.5,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Mandible bone,NaN,NaN,pT4aN3b,positive,4,NaN
15,NaN,617192,KUMC,HNSCC,2025-08-27 00:00:00,7:00am,2025-08-28 00:00:00,10:30am,10.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT3N0,negative*,3,Notes papilary thyroid cancer in lymph node?
16,NaN,616204,KUMC,HNSCC,2025-05-29 00:00:00,10:44am,2025-05-30 00:00:00,11:25am,8.2,1.0,...,Not Hispanic or Latino,Tongue squamous cell carcinoma,Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN,NaN
17,NaN,615727,KUMC,HNSCC,2025-04-22 00:00:00,6:52am,2025-04-23 00:00:00,1:30pm,6.0,1.0,...,Not Hispanic or Latino,HPV mediated squamous cell carcinoma of the or...,HPV mediated squamous cell carcinoma,"oropharynx, tonsil",NaN,Positive,pT2pN1,positive,3,NaN
18,NaN,616689,KUMC,HNSCC,2025-07-14 00:00:00,NaN,2025-07-15 00:00:00,11:00am,5.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Good,615338,KUMC,HNSCC,2025-03-25 00:00:00,6:28am,2025-03-26 00:00:00,12:00pm,NaN,NaN,...,Hispanic or Latino,"Squamous cell carcinoma, moderate to poorly di...",Squamous cell carcinoma,tongue,NaN,NaN,pT4apN0,negative,4,NaN
20,NaN,616521,KUMC,HNSCC,2025-06-25 00:00:00,6:54am,2025-06-26 00:00:00,NaN,8.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Gum,NaN,NaN,pT2pN0,negative,2,NaN
21,NaN,616262,KUMC,HNSCC,2025-06-03 00:00:00,9:20am,2025-06-04 00:00:00,1:15pm,9.0,1.0,...,Not Hispanic or Latino,"Invasive, moderately differentiated keratinizi...",Squamous cell carcinoma of the oral cavity,Oral cavity,NaN,NaN,pT4apN0,negative,4,NaN
22,NaN,611398,KUMC,HNSCC,2024-03-26 00:00:00,11:14am,2024-03-02 00:00:00,2:44pm,7.2,1.0,...,Not Hispanic or Latino,Human papillomavirus (HPV)-mediated squamous c...,HPV mediated squamous cell carcinoma,"Tonsil, oropharynx, lymph node",positive,Positive,PT1 pN1 ENE (+),Positive,1,NaN
23,Good,614112,KUMC,HNSCC,2024-12-09 00:00:00,6:18am,2024-12-10 00:00:00,1:30pm,7.7,1.0,...,Not Hispanic or Latino,"Oropharyngeal squamous cell carcinoma, HPV ass...",Oropharyngeal Squamous cell carcinoma,Tonsil,NaN,postive,pT1,negative,1,NaN
24,Good,7722,KUMC,HNSCC,2024-12-09 00:00:00,8:27am,2024-12-10 00:00:00,1:30pm,9.4,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN,NaN
25,Good,614957,KUMC,HNSCC,2025-02-25 00:00:00,6:45am,2025-02-26 00:00:00,1:00pm,5.0,1.0,...,Not Hispanic or Latino,Human papillomavirus / HPV-mediated squamous ...,HPV mediated squamous cell carcinoma,oropharynx,positive,positive,pT2pN1,Positive,3,NaN
26,Good,614956,KUMC,HNSCC,2025-02-25 00:00:00,6:28am,2025-02-26 00:00:00,1:00pm,5.0,1.0,...,Not Hispanic or Latino,Invasive moderately to poorly differentiated s...,Squamous cell carcinoma,tongue,positive,NaN,pT4apN3b,Positive,4,NaN
27,?,612489,KUMC,Healthy,2025-08-27 00:00:00,7:30am,2025-08-28 00:00:00,10:30am,8.5,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,617188,KUMC,Healthy,2025-08-26 00:00:00,10:00am,2025-08-27 00:00:00,2:00pm,7.0,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,613164,KUMC,Healthy,2025-08-04 00:00:00,10:55am,2025-08-05 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,612589,KUMC,Healthy,2025-07-29 00:00:00,9:45am,2025-07-30 00:00:00,12:30pm,16.0,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,616517,KUMC,Healthy,2025-06-25 00:00:00,8:55am,2025-06-26 00:00:00,NaN,5.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,616352,KUMC,Healthy,2025-06-09 00:00:00,1:39pm,2025-06-10 00:00:00,1:30pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,616322,KUMC,Healthy,2025-06-05 00:00:00,10:35am,2025-06-06 00:00:00,1:00pm,7.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,608925,KUMC,Healthy,2025-05-29 00:00:00,9:06am,2025-05-30 00:00:00,11:25am,8.7,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,011536_V08-1,KUMC,Healthy,2025-04-22 00:00:00,14:28am,2025-04-23 00:00:00,1:30pm,10.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,615632,KUMC,Healthy,2025-04-15 00:00:00,NaN,2025-04-16 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,24364,KUMC,Healthy,2025-04-14 00:00:00,9:54am,2025-04-15 00:00:00,10:00am,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,615565,KUMC,Healthy,2025-04-10 00:00:00,7:35am,2025-04-11 00:00:00,1:50pm,10.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Good,615349,KUMC,Healthy,2025-03-25 00:00:00,6:33am,2025-03-26 00:00:00,12:00pm,NaN,1.0,...,Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Good,609149,KUMC,Healthy,2025-02-25 00:00:00,6:47am,2025-02-26 00:00:00,1:00pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Good,7420,KUMC,Healthy,2025-02-25 00:00:00,8:45am,2025-02-26 00:00:00,1:00pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Good,610891,KUMC,Healthy,2025-01-21 00:00:00,8:15am,2025-01-22 00:00:00,10:20am,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Good,8980,KUMC,Healthy,2024-12-09 00:00:00,12:17pm,2024-12-10 00:00:00,1:30pm,8.5,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.drop(0, inplace = True)
df

,QC,Patient ID,Source,Diagnosis,Ship Date,Ship/Draw Time (CST),Staining Date,Staining Time (PST),Total Volume (ml),Volume for Staining,...,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage,Unnamed: 38
1,NaN,616919,KUMC,HNSCC,2025-08-04 00:00:00,6:43am,2025-08-05 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT4aN0,negative,4,NaN
2,NaN,611553,KUMC,HNSCC,2024-04-11 00:00:00,6:42am,2024-04-12 00:00:00,2:55pm,7.3,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, well-to moderately di...",Squamous cell carcinoma,"Tongue/oral cavity, Pharynx",negative,NaN,pT4a N0 M (N/A),negative,3,NaN
3,NaN,611620,KUMC,HNSCC,2024-04-18 00:00:00,6:30am,2024-04-19 00:00:00,11:55am,9.0,1.0,...,Not Hispanic or Latino,HPV-mediated squamous cell carcinoma of the ri...,HPV mediated squamous cell carcinoma,Tonsil,NaN,Positive,NaN,NaN,NaN,NaN
4,Good,614851,KUMC,HNSCC,2025-02-17 00:00:00,7:40am,2025-02-18 00:00:00,12:15pm,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,tongue,NaN,NaN,pT1pN0,negative,1,NaN
5,Good,614476,KUMC,HNSCC,2025-01-21 00:00:00,7:13am,2025-01-22 00:00:00,10:20am,9.0,1.0,...,Not Hispanic or Latino,"Invasive, moderately differentiated keratiniz...",Squamous cell carcinoma,Lip,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,617177,KUMC,HNSCC,2025-08-26 00:00:00,6:28am,2025-08-27 00:00:00,2:00pm,8.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,"Oral mucosa, tongue",NaN,NaN,pT4aN3b,positive,4,NaN
7,NaN,611603,KUMC,HNSCC,2024-04-17 00:00:00,9:48am,2024-04-18 00:00:00,10:45am,6.2,1.0,...,Not Hispanic or Latino,"invasive squamous cell carcinoma, well to mode...",Invasive squamous cell carcinoma,Tongue,negative,NaN,NaN,NaN,NaN,NaN
8,NaN,616671,KUMC,HNSCC,2025-07-14 00:00:00,7:25am,2025-07-15 00:00:00,11:00am,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, with po...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,negative,NaN,NaN,NaN,NaN
9,NaN,616701,KUMC,HNSCC,2025-07-15 00:00:00,6:24am,2025-07-16 00:00:00,12:00pm,9.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,NaN,pT4aN0,negative,4,NaN
10,NaN,615538,KUMC,HNSCC,2025-04-09 00:00:00,6:14am,2025-04-10 00:00:00,12:15pm,9.0,1.0,...,Not Hispanic or Latino,Moderately differentiated squamous cell carcin...,Squamous cell carcinoma,gingival mucosa,NaN,NaN,pT2pN0,negative,2,NaN
11,Good,615576,KUMC,HNSCC,2025-04-14 00:00:00,8:30am,2025-04-15 00:00:00,10:00am,6.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, invasive, keratinizin...",Squamous cell carcinoma,tongue,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,616494,KUMC,HNSCC,2025-06-25 00:00:00,6:38am,2025-06-26 00:00:00,NaN,8.0,1.0,...,Not Hispanic or Latino,Human papillomavirus (HPV)-associated squamous...,HPV mediated squamous cell carcinoma,Tonsil,NaN,postive,pT2pN2,postitive,4,NaN
13,NaN,616343,KUMC,HNSCC,2025-06-09 00:00:00,6:58am,2025-06-10 00:00:00,1:30pm,3.0,1.0,...,Not Hispanic or Latino,Squamous cell carcinoma,Squamous cell carcinoma of the oral cavity,"Neck, Oral cavity",NaN,NaN,pT2pN1,Positive,3,NaN
14,NaN,616861,KUMC,HNSCC,2025-07-29 00:00:00,6:39am,2025-07-30 00:00:00,12:30pm,8.5,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Mandible bone,NaN,NaN,pT4aN3b,positive,4,NaN
15,NaN,617192,KUMC,HNSCC,2025-08-27 00:00:00,7:00am,2025-08-28 00:00:00,10:30am,10.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT3N0,negative*,3,Notes papilary thyroid cancer in lymph node?
16,NaN,616204,KUMC,HNSCC,2025-05-29 00:00:00,10:44am,2025-05-30 00:00:00,11:25am,8.2,1.0,...,Not Hispanic or Latino,Tongue squamous cell carcinoma,Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN,NaN
17,NaN,615727,KUMC,HNSCC,2025-04-22 00:00:00,6:52am,2025-04-23 00:00:00,1:30pm,6.0,1.0,...,Not Hispanic or Latino,HPV mediated squamous cell carcinoma of the or...,HPV mediated squamous cell carcinoma,"oropharynx, tonsil",NaN,Positive,pT2pN1,positive,3,NaN
18,NaN,616689,KUMC,HNSCC,2025-07-14 00:00:00,NaN,2025-07-15 00:00:00,11:00am,5.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Good,615338,KUMC,HNSCC,2025-03-25 00:00:00,6:28am,2025-03-26 00:00:00,12:00pm,NaN,NaN,...,Hispanic or Latino,"Squamous cell carcinoma, moderate to poorly di...",Squamous cell carcinoma,tongue,NaN,NaN,pT4apN0,negative,4,NaN
20,NaN,616521,KUMC,HNSCC,2025-06-25 00:00:00,6:54am,2025-06-26 00:00:00,NaN,8.0,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Gum,NaN,NaN,pT2pN0,negative,2,NaN
21,NaN,616262,KUMC,HNSCC,2025-06-03 00:00:00,9:20am,2025-06-04 00:00:00,1:15pm,9.0,1.0,...,Not Hispanic or Latino,"Invasive, moderately differentiated keratinizi...",Squamous cell carcinoma of the oral cavity,Oral cavity,NaN,NaN,pT4apN0,negative,4,NaN
22,NaN,611398,KUMC,HNSCC,2024-03-26 00:00:00,11:14am,2024-03-02 00:00:00,2:44pm,7.2,1.0,...,Not Hispanic or Latino,Human papillomavirus (HPV)-mediated squamous c...,HPV mediated squamous cell carcinoma,"Tonsil, oropharynx, lymph node",positive,Positive,PT1 pN1 ENE (+),Positive,1,NaN
23,Good,614112,KUMC,HNSCC,2024-12-09 00:00:00,6:18am,2024-12-10 00:00:00,1:30pm,7.7,1.0,...,Not Hispanic or Latino,"Oropharyngeal squamous cell carcinoma, HPV ass...",Oropharyngeal Squamous cell carcinoma,Tonsil,NaN,postive,pT1,negative,1,NaN
24,Good,7722,KUMC,HNSCC,2024-12-09 00:00:00,8:27am,2024-12-10 00:00:00,1:30pm,9.4,1.0,...,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN,NaN
25,Good,614957,KUMC,HNSCC,2025-02-25 00:00:00,6:45am,2025-02-26 00:00:00,1:00pm,5.0,1.0,...,Not Hispanic or Latino,Human papillomavirus / HPV-mediated squamous ...,HPV mediated squamous cell carcinoma,oropharynx,positive,positive,pT2pN1,Positive,3,NaN
26,Good,614956,KUMC,HNSCC,2025-02-25 00:00:00,6:28am,2025-02-26 00:00:00,1:00pm,5.0,1.0,...,Not Hispanic or Latino,Invasive moderately to poorly differentiated s...,Squamous cell carcinoma,tongue,positive,NaN,pT4apN3b,Positive,4,NaN
27,?,612489,KUMC,Healthy,2025-08-27 00:00:00,7:30am,2025-08-28 00:00:00,10:30am,8.5,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,617188,KUMC,Healthy,2025-08-26 00:00:00,10:00am,2025-08-27 00:00:00,2:00pm,7.0,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,613164,KUMC,Healthy,2025-08-04 00:00:00,10:55am,2025-08-05 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,612589,KUMC,Healthy,2025-07-29 00:00:00,9:45am,2025-07-30 00:00:00,12:30pm,16.0,1.0,...,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,616517,KUMC,Healthy,2025-06-25 00:00:00,8:55am,2025-06-26 00:00:00,NaN,5.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,616352,KUMC,Healthy,2025-06-09 00:00:00,1:39pm,2025-06-10 00:00:00,1:30pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,616322,KUMC,Healthy,2025-06-05 00:00:00,10:35am,2025-06-06 00:00:00,1:00pm,7.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,608925,KUMC,Healthy,2025-05-29 00:00:00,9:06am,2025-05-30 00:00:00,11:25am,8.7,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,011536_V08-1,KUMC,Healthy,2025-04-22 00:00:00,14:28am,2025-04-23 00:00:00,1:30pm,10.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,615632,KUMC,Healthy,2025-04-15 00:00:00,NaN,2025-04-16 00:00:00,NaN,NaN,NaN,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,24364,KUMC,Healthy,2025-04-14 00:00:00,9:54am,2025-04-15 00:00:00,10:00am,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,615565,KUMC,Healthy,2025-04-10 00:00:00,7:35am,2025-04-11 00:00:00,1:50pm,10.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Good,615349,KUMC,Healthy,2025-03-25 00:00:00,6:33am,2025-03-26 00:00:00,12:00pm,NaN,1.0,...,Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Good,609149,KUMC,Healthy,2025-02-25 00:00:00,6:47am,2025-02-26 00:00:00,1:00pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Good,7420,KUMC,Healthy,2025-02-25 00:00:00,8:45am,2025-02-26 00:00:00,1:00pm,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Good,610891,KUMC,Healthy,2025-01-21 00:00:00,8:15am,2025-01-22 00:00:00,10:20am,9.0,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Good,8980,KUMC,Healthy,2024-12-09 00:00:00,12:17pm,2024-12-10 00:00:00,1:30pm,8.5,1.0,...,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.columns

Index(['QC', 'Patient ID', 'Source', 'Diagnosis', 'Ship Date',
       'Ship/Draw Time (CST)', 'Staining Date', 'Staining Time (PST)',
       'Total Volume (ml)', 'Volume for Staining', 'Volume to PBMCs/plasama',
       'Staining Cell Count, Live', 'Staining Cell Count, dead ',
       'Staining Cells, Viability', 'PBMCs/Plasma cell count, live',
       'PBMCs/Plasama, cell count dead', 'PBMCS/Plasma, viability',
       'Plasma vials (100ul)', 'Plasma vials, other',
       'PBMCs, 10 million cells', 'PBMCs, other', 'Notes', '% Neutrophils',
       '% CD79b+ Neutrophils', '% CD79b+ Neutrophils.1', 'CD79b+ neutrophils',
       'Age', 'Sex', 'Race', 'Ethnicity',
       'Diagnosis (as listed in KUMC excel)', 'Final Diagnosis ', 'Location',
       'Metastisis', 'HPV status', 'staging', 'lymph node stage',
       'Calculated Stage ', 'Unnamed: 38'],
      dtype='object')

In [34]:
df_partial_clean = df.drop(['QC', 'Source', 'Ship Date', 'Ship/Draw Time (CST)', 'Staining Date', 'Staining Time (PST)', 'Total Volume (ml)', 'Volume for Staining', 'Volume to PBMCs/plasama', 'Staining Cell Count, Live', 'Staining Cell Count, dead ', 'Staining Cells, Viability', 'PBMCs/Plasma cell count, live', 'PBMCs/Plasama, cell count dead', 'PBMCS/Plasma, viability', 'Plasma vials (100ul)', 'Plasma vials, other', 'PBMCs, 10 million cells', 'PBMCs, other', 'Notes', 'Unnamed: 38'], axis = 1)
df_partial_clean

,Patient ID,Diagnosis,% Neutrophils,% CD79b+ Neutrophils,% CD79b+ Neutrophils.1,CD79b+ neutrophils,Age,Sex,Race,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage
1,616919,HNSCC,64.692559,16.401306,25.352693,1.851707e+06,35.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT4aN0,negative,4
2,611553,HNSCC,71.077168,1.659306,2.334513,1.616993e+06,77.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, well-to moderately di...",Squamous cell carcinoma,"Tongue/oral cavity, Pharynx",negative,NaN,pT4a N0 M (N/A),negative,3
3,611620,HNSCC,58.012654,1.592854,2.745702,1.326848e+06,70.0,Male,White,Not Hispanic or Latino,HPV-mediated squamous cell carcinoma of the ri...,HPV mediated squamous cell carcinoma,Tonsil,NaN,Positive,NaN,NaN,NaN
4,614851,HNSCC,70.41828,10.309837,14.6,1.154702e+06,83.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,tongue,NaN,NaN,pT1pN0,negative,1
5,614476,HNSCC,35.8,1.58509,4.43,1.036649e+06,63.0,Male,White,Not Hispanic or Latino,"Invasive, moderately differentiated keratiniz...",Squamous cell carcinoma,Lip,NaN,NaN,NaN,NaN,NaN
6,617177,HNSCC,59.082132,15.575825,26.363004,9.843921e+05,73.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,"Oral mucosa, tongue",NaN,NaN,pT4aN3b,positive,4
7,611603,HNSCC,45.770065,1.084599,2.369668,9.685466e+05,59.0,Female,White,Not Hispanic or Latino,"invasive squamous cell carcinoma, well to mode...",Invasive squamous cell carcinoma,Tongue,negative,NaN,NaN,NaN,NaN
8,616671,HNSCC,52.54102,16.622619,31.637412,8.926346e+05,82.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, with po...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,negative,NaN,NaN,NaN
9,616701,HNSCC,51.127396,6.581172,12.872106,8.762831e+05,67.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,NaN,pT4aN0,negative,4
10,615538,HNSCC,70.184651,2.200405,3.135166,5.619835e+05,49.0,Male,White,Not Hispanic or Latino,Moderately differentiated squamous cell carcin...,Squamous cell carcinoma,gingival mucosa,NaN,NaN,pT2pN0,negative,2
11,615576,HNSCC,72.000821,17.964293,24.950123,5.506954e+05,83.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, invasive, keratinizin...",Squamous cell carcinoma,tongue,NaN,NaN,NaN,NaN,NaN
12,616494,HNSCC,65.447223,10.547072,16.115385,4.993511e+05,57.0,Male,White,Not Hispanic or Latino,Human papillomavirus (HPV)-associated squamous...,HPV mediated squamous cell carcinoma,Tonsil,NaN,postive,pT2pN2,postitive,4
13,616343,HNSCC,56.003139,9.424162,16.827918,4.735641e+05,60.0,Female,White,Not Hispanic or Latino,Squamous cell carcinoma,Squamous cell carcinoma of the oral cavity,"Neck, Oral cavity",NaN,NaN,pT2pN1,Positive,3
14,616861,HNSCC,50.834092,1.347545,2.650869,3.258365e+05,43.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Mandible bone,NaN,NaN,pT4aN3b,positive,4
15,617192,HNSCC,61.225209,1.019539,1.665227,2.942898e+05,56.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT3N0,negative*,3
16,616204,HNSCC,74.972412,0.651808,0.869398,2.528365e+05,56.0,Female,White,Not Hispanic or Latino,Tongue squamous cell carcinoma,Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN
17,615727,HNSCC,46.261079,7.546683,16.313244,2.020247e+05,61.0,Female,White,Not Hispanic or Latino,HPV mediated squamous cell carcinoma of the or...,HPV mediated squamous cell carcinoma,"oropharynx, tonsil",NaN,Positive,pT2pN1,positive,3
18,616689,HNSCC,33.644002,2.572194,7.645327,1.701506e+05,82.0,Female,Black or African American,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,615338,HNSCC,60.905829,5.97659,9.81,1.596347e+05,32.0,Female,White,Hispanic or Latino,"Squamous cell carcinoma, moderate to poorly di...",Squamous cell carcinoma,tongue,NaN,NaN,pT4apN0,negative,4
20,616521,HNSCC,60.606628,2.752294,4.541242,1.515138e+05,78.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Gum,NaN,NaN,pT2pN0,negative,2
21,616262,HNSCC,60.511612,3.085167,5.098471,1.252578e+05,74.0,Male,White,Not Hispanic or Latino,"Invasive, moderately differentiated keratinizi...",Squamous cell carcinoma of the oral cavity,Oral cavity,NaN,NaN,pT4apN0,negative,4
22,611398,HNSCC,76.987091,0.138696,1.801663,5.475728e+04,42.0,Male,White,Not Hispanic or Latino,Human papillomavirus (HPV)-mediated squamous c...,HPV mediated squamous cell carcinoma,"Tonsil, oropharynx, lymph node",positive,Positive,PT1 pN1 ENE (+),Positive,1
23,614112,HNSCC,46.5,1.84,3.97,9.328800e+05,51.0,Male,White,Not Hispanic or Latino,"Oropharyngeal squamous cell carcinoma, HPV ass...",Oropharyngeal Squamous cell carcinoma,Tonsil,NaN,postive,pT1,negative,1
24,7722,HNSCC,66.2,0.72,1.09,2.625120e+05,76.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN
25,614957,HNSCC,7.49,0.69,9.18,1.250625e+05,58.0,Male,White,Not Hispanic or Latino,Human papillomavirus / HPV-mediated squamous ...,HPV mediated squamous cell carcinoma,oropharynx,positive,positive,pT2pN1,Positive,3
26,614956,HNSCC,20.9,0.91,4.37,9.227400e+04,51.0,Male,White,Not Hispanic or Latino,Invasive moderately to poorly differentiated s...,Squamous cell carcinoma,tongue,positive,NaN,pT4apN3b,Positive,4
27,612489,Healthy,47.589761,2.62633,5.518687,5.621659e+05,53.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,617188,Healthy,44.049085,4.350324,9.876083,2.838587e+05,78.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,613164,Healthy,76.175446,9.079729,11.919496,5.997161e+05,40.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,612589,Healthy,53.570242,1.942876,3.626782,3.406833e+05,42.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,616517,Healthy,35.961529,2.038772,5.669313,5.871663e+04,57.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,616352,Healthy,56.69284,14.324211,25.26635,5.629415e+05,56.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,616322,Healthy,59.429762,4.481026,7.540037,1.720714e+05,62.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,608925,Healthy,42.883072,1.222419,2.850586,5.273516e+05,52.0,Female,Black or African American,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,011536_V08-1,Healthy,45.475354,1.421271,3.125366,3.547493e+04,59.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,615632,Healthy,43.473032,4.268665,9.81911,0.000000e+00,60.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,24364,Healthy,48.112604,2.712021,5.63682,5.814573e+04,81.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,615565,Healthy,62.685922,2.373017,3.785567,7.435850e+05,48.0,Male,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,615349,Healthy,38.459323,0.973295,2.53,2.488230e+04,28.0,Male,Other,Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,609149,Healthy,61.2,0.665557,1.09,8.199667e+04,78.0,Male,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,7420,Healthy,57.7,1.415419,2.45,1.784136e+05,51.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,610891,Healthy,33.4,0.38,1.13,2.247700e+05,59.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,8980,Healthy,26.9,0.35,1.32,1.818250e+05,46.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
hnscc = []
healthy = []

for row in df_partial_clean.itertuples():
    if row[2] == 'HNSCC':
        hnscc.append(row)
    elif row[2] == 'Healthy':
        healthy.append(row)

# hnscc and healthy are lists of tuples, so we need to convert them to dataframes where first column in the tuple is the index and the rest are the columns
# index is the first column in the tuple, so we need to drop it from the tuple first before converting to dataframe

hnscc_df = pd.DataFrame([row[1:] for row in hnscc], columns = df_partial_clean.columns)
healthy_df = pd.DataFrame([row[1:] for row in healthy], columns = df_partial_clean.columns)

hnscc_df
healthy_df

,Patient ID,Diagnosis,% Neutrophils,% CD79b+ Neutrophils,% CD79b+ Neutrophils.1,CD79b+ neutrophils,Age,Sex,Race,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage
0,612489,Healthy,47.589761,2.626330,5.518687,562165.890957,53.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,617188,Healthy,44.049085,4.350324,9.876083,283858.655504,78.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,613164,Healthy,76.175446,9.079729,11.919496,599716.130355,40.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,612589,Healthy,53.570242,1.942876,3.626782,340683.327798,42.0,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,616517,Healthy,35.961529,2.038772,5.669313,58716.625758,57.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,616352,Healthy,56.692840,14.324211,25.266350,562941.504437,56.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,616322,Healthy,59.429762,4.481026,7.540037,172071.402312,62.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,608925,Healthy,42.883072,1.222419,2.850586,527351.571213,52.0,Female,Black or African American,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,011536_V08-1,Healthy,45.475354,1.421271,3.125366,35474.928138,59.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,615632,Healthy,43.473032,4.268665,9.819110,0.000000,60.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,24364,Healthy,48.112604,2.712021,5.636820,58145.731144,81.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,615565,Healthy,62.685922,2.373017,3.785567,743584.984262,48.0,Male,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,615349,Healthy,38.459323,0.973295,2.530000,24882.296665,28.0,Male,Other,Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,609149,Healthy,61.200000,0.665557,1.090000,81996.672213,78.0,Male,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,7420,Healthy,57.700000,1.415419,2.450000,178413.551325,51.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,610891,Healthy,33.400000,0.380000,1.130000,224770.000000,59.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,8980,Healthy,26.900000,0.350000,1.320000,181825.000000,46.0,Female,White,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
hnscc_clean = hnscc_df.drop(['Diagnosis', 'Patient ID'], axis = 1)
healthy_clean = healthy_df.drop(['Diagnosis', 'Diagnosis (as listed in KUMC excel)', 'Patient ID'], axis = 1)

In [68]:
hnscc_clean

,% Neutrophils,% CD79b+ Neutrophils,% CD79b+ Neutrophils.1,CD79b+ neutrophils,Age,Sex,Race,Ethnicity,Diagnosis (as listed in KUMC excel),Final Diagnosis,Location,Metastisis,HPV status,staging,lymph node stage,Calculated Stage
0,64.692559,16.401306,25.352693,1.851707e+06,35.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT4aN0,negative,4.0
1,71.077168,1.659306,2.334513,1.616993e+06,77.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, well-to moderately di...",Squamous cell carcinoma,"Tongue/oral cavity, Pharynx",negative,NaN,pT4a N0 M (N/A),negative,3.0
2,58.012654,1.592854,2.745702,1.326848e+06,70.0,Male,White,Not Hispanic or Latino,HPV-mediated squamous cell carcinoma of the ri...,HPV mediated squamous cell carcinoma,Tonsil,NaN,Positive,NaN,NaN,NaN
3,70.418280,10.309837,14.600000,1.154702e+06,83.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,tongue,NaN,NaN,pT1pN0,negative,1.0
4,35.800000,1.585090,4.430000,1.036649e+06,63.0,Male,White,Not Hispanic or Latino,"Invasive, moderately differentiated keratiniz...",Squamous cell carcinoma,Lip,NaN,NaN,NaN,NaN,NaN
5,59.082132,15.575825,26.363004,9.843921e+05,73.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,"Oral mucosa, tongue",NaN,NaN,pT4aN3b,positive,4.0
6,45.770065,1.084599,2.369668,9.685466e+05,59.0,Female,White,Not Hispanic or Latino,"invasive squamous cell carcinoma, well to mode...",Invasive squamous cell carcinoma,Tongue,negative,NaN,NaN,NaN,NaN
7,52.541020,16.622619,31.637412,8.926346e+05,82.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, with po...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,negative,NaN,NaN,NaN
8,51.127396,6.581172,12.872106,8.762831e+05,67.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Tongue,NaN,NaN,pT4aN0,negative,4.0
9,70.184651,2.200405,3.135166,5.619835e+05,49.0,Male,White,Not Hispanic or Latino,Moderately differentiated squamous cell carcin...,Squamous cell carcinoma,gingival mucosa,NaN,NaN,pT2pN0,negative,2.0
10,72.000821,17.964293,24.950123,5.506954e+05,83.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, invasive, keratinizin...",Squamous cell carcinoma,tongue,NaN,NaN,NaN,NaN,NaN
11,65.447223,10.547072,16.115385,4.993511e+05,57.0,Male,White,Not Hispanic or Latino,Human papillomavirus (HPV)-associated squamous...,HPV mediated squamous cell carcinoma,Tonsil,NaN,postive,pT2pN2,postitive,4.0
12,56.003139,9.424162,16.827918,4.735641e+05,60.0,Female,White,Not Hispanic or Latino,Squamous cell carcinoma,Squamous cell carcinoma of the oral cavity,"Neck, Oral cavity",NaN,NaN,pT2pN1,Positive,3.0
13,50.834092,1.347545,2.650869,3.258365e+05,43.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Mandible bone,NaN,NaN,pT4aN3b,positive,4.0
14,61.225209,1.019539,1.665227,2.942898e+05,56.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, conventional (keratin...",Squamous cell carcinoma,Tongue,NaN,NaN,pT3N0,negative*,3.0
15,74.972412,0.651808,0.869398,2.528365e+05,56.0,Female,White,Not Hispanic or Latino,Tongue squamous cell carcinoma,Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN
16,46.261079,7.546683,16.313244,2.020247e+05,61.0,Female,White,Not Hispanic or Latino,HPV mediated squamous cell carcinoma of the or...,HPV mediated squamous cell carcinoma,"oropharynx, tonsil",NaN,Positive,pT2pN1,positive,3.0
17,33.644002,2.572194,7.645327,1.701506e+05,82.0,Female,Black or African American,Not Hispanic or Latino,Healthy,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60.905829,5.976590,9.810000,1.596347e+05,32.0,Female,White,Hispanic or Latino,"Squamous cell carcinoma, moderate to poorly di...",Squamous cell carcinoma,tongue,NaN,NaN,pT4apN0,negative,4.0
19,60.606628,2.752294,4.541242,1.515138e+05,78.0,Male,White,Not Hispanic or Latino,"Squamous cell carcinoma, moderately differenti...",Squamous cell carcinoma of the oral cavity,Gum,NaN,NaN,pT2pN0,negative,2.0
20,60.511612,3.085167,5.098471,1.252578e+05,74.0,Male,White,Not Hispanic or Latino,"Invasive, moderately differentiated keratinizi...",Squamous cell carcinoma of the oral cavity,Oral cavity,NaN,NaN,pT4apN0,negative,4.0
21,76.987091,0.138696,1.801663,5.475728e+04,42.0,Male,White,Not Hispanic or Latino,Human papillomavirus (HPV)-mediated squamous c...,HPV mediated squamous cell carcinoma,"Tonsil, oropharynx, lymph node",positive,Positive,PT1 pN1 ENE (+),Positive,1.0
22,46.500000,1.840000,3.970000,9.328800e+05,51.0,Male,White,Not Hispanic or Latino,"Oropharyngeal squamous cell carcinoma, HPV ass...",Oropharyngeal Squamous cell carcinoma,Tonsil,NaN,postive,pT1,negative,1.0
23,66.200000,0.720000,1.090000,2.625120e+05,76.0,Female,White,Not Hispanic or Latino,"Squamous cell carcinoma, keratinizing, moderat...",Squamous cell carcinoma,Tongue,NaN,negative,NaN,NaN,NaN
24,7.490000,0.690000,9.180000,1.250625e+05,58.0,Male,White,Not Hispanic or Latino,Human papillomavirus / HPV-mediated squamous ...,HPV mediated squamous cell carcinoma,oropharynx,positive,positive,pT2pN1,Positive,3.0
25,20.900000,0.910000,4.370000,9.227400e+04,51.0,Male,White,Not Hispanic or Latino,Invasive moderately to poorly differentiated s...,Squamous cell carcinoma,tongue,positive,NaN,pT4apN3b,Positive,4.0